name: Build Board Images
on: [push]
jobs:
  build-images:
    strategy:
      matrix:
        board_name:
          # from `make list-defconfigs`
          - aarch64_efi_defconfig
          - acmesystems_acqua_a5_256mb_defconfig
          - acmesystems_acqua_a5_512mb_defconfig
          - acmesystems_aria_g25_128mb_defconfig
          - acmesystems_aria_g25_256mb_defconfig
          - acmesystems_arietta_g25_128mb_defconfig
          - acmesystems_arietta_g25_256mb_defconfig
          - amarula_vyasa_rk3288_defconfig
          - andes_ae350_45_defconfig
          - arcturus_ucls1012a_defconfig
          - arcturus_ucp1020_defconfig
          - arm_foundationv8_defconfig
          - armadeus_apf27_defconfig
          - armadeus_apf28_defconfig
          - armadeus_apf51_defconfig
          - aspeed_ast2500evb_defconfig
          - aspeed_ast2600evb_defconfig
          - asus_tinker_rk3288_defconfig
          - at91sam9260eknf_defconfig
          - at91sam9g20dfc_defconfig
          - at91sam9g45m10ek_defconfig
          - at91sam9rlek_defconfig
          - at91sam9x5ek_defconfig
          - at91sam9x5ek_dev_defconfig
          - at91sam9x5ek_mmc_defconfig
          - at91sam9x5ek_mmc_dev_defconfig
          - atmel_sama5d2_xplained_mmc_defconfig
          - atmel_sama5d2_xplained_mmc_dev_defconfig
          - atmel_sama5d27_som1_ek_mmc_dev_defconfig
          - atmel_sama5d3_xplained_defconfig
          - atmel_sama5d3_xplained_dev_defconfig
          - atmel_sama5d3_xplained_mmc_defconfig
          - atmel_sama5d3_xplained_mmc_dev_defconfig
          - atmel_sama5d3xek_defconfig
          - atmel_sama5d4_xplained_defconfig
          - atmel_sama5d4_xplained_dev_defconfig
          - atmel_sama5d4_xplained_mmc_defconfig
          - atmel_sama5d4_xplained_mmc_dev_defconfig
          - avenger96_defconfig
          - bananapi_m2_ultra_defconfig
          - bananapi_m2_zero_defconfig
          - bananapro_defconfig
          - beagleboardx15_defconfig
          - beaglebone_defconfig
          - beaglebone_qt5_defconfig
          - beagleboneai_defconfig
          - beaglev_defconfig
          - beelink_gs1_defconfig
          - broadcom_northstar_defconfig
          - canaan_kd233_defconfig
          - chromebook_elm_defconfig
          - chromebook_snow_defconfig
          - ci20_defconfig
          - cubieboard2_defconfig
          - engicam_imx6qdl_icore_defconfig
          - engicam_imx6qdl_icore_qt5_defconfig
          - engicam_imx6qdl_icore_rqs_defconfig
          - engicam_imx6ul_geam_defconfig
          - engicam_imx6ul_isiot_defconfig
          - freescale_imx28evk_defconfig
          - freescale_imx6dlsabreauto_defconfig
          - freescale_imx6dlsabresd_defconfig
          - freescale_imx6qsabreauto_defconfig
          - freescale_imx6qsabresd_defconfig
          - freescale_imx6sxsabresd_defconfig
          - freescale_imx6ullevk_defconfig
          - freescale_imx7dsabresd_defconfig
          - freescale_imx8mmevk_defconfig
          - freescale_imx8mnevk_defconfig
          - freescale_imx8mpevk_defconfig
          - freescale_imx8mqevk_defconfig
          - freescale_imx8qmmek_defconfig
          - freescale_imx8qxpmek_defconfig
          - freescale_p1025twr_defconfig
          - freescale_t1040d4rdb_defconfig
          - freescale_t2080_qds_rdb_defconfig
          - friendlyarm_nanopi_r2s_defconfig
          - galileo_defconfig
          - globalscale_espressobin_defconfig
          - grinn_chiliboard_defconfig
          - grinn_liteboard_defconfig
          - hifive_unleashed_defconfig
          - imx23evk_defconfig
          - imx6-sabreauto_defconfig
          - imx6-sabresd_defconfig
          - imx6-sabresd_qt5_defconfig
          - imx6slevk_defconfig
          - imx6sx-sdb_defconfig
          - imx6ulevk_defconfig
          - imx6ullevk_defconfig
          - imx6ulpico_defconfig
          - imx7d-sdb_defconfig
          - imx7dpico_defconfig
          - imx8mmpico_defconfig
          - imx8mn_bsh_smm_s2_defconfig
          - imx8mn_bsh_smm_s2_pro_defconfig
          - imx8mpico_defconfig
          - imx8mqevk_defconfig
          - kontron_bl_imx8mm_defconfig
          - kontron_pitx_imx8m_defconfig
          - kontron_smarc_sal28_defconfig
          - lafrite_defconfig
          - lego_ev3_defconfig
          - licheepi_zero_defconfig
          - linksprite_pcduino_defconfig
          - ls1028ardb_defconfig
          - mender_x86_64_efi_defconfig
          - microchip_sam9x60ek_mmc_defconfig
          - microchip_sam9x60ek_mmc_dev_defconfig
          - microchip_sama5d2_icp_mmc_defconfig
          - microchip_sama5d2_icp_mmc_dev_defconfig
          - microchip_sama5d27_wlsom1_ek_mmc_defconfig
          - microchip_sama5d27_wlsom1_ek_mmc_dev_defconfig
          - microchip_sama7g5ek_mmc_defconfig
          - microchip_sama7g5ek_mmc_dev_defconfig
          - minnowboard_max_defconfig
          - mx25pdk_defconfig
          - mx51evk_defconfig
          - mx53loco_defconfig
          - mx6cubox_defconfig
          - mx6sx_udoo_neo_defconfig
          - mx6udoo_defconfig
          - nexbox_a95x_defconfig
          - nezha_defconfig
          - nitrogen6sx_defconfig
          - nitrogen6x_defconfig
          - nitrogen7_defconfig
          - nitrogen8m_defconfig
          - nitrogen8mm_defconfig
          - nitrogen8mn_defconfig
          - nitrogen8mp_defconfig
          - octavo_osd32mp1_brk_defconfig
          - octavo_osd32mp1_red_defconfig
          - odroidc2_defconfig
          - odroidxu4_defconfig
          - olimex_a10_olinuxino_lime_defconfig
          - olimex_a13_olinuxino_defconfig
          - olimex_a20_olinuxino_lime_defconfig
          - olimex_a20_olinuxino_lime2_defconfig
          - olimex_a20_olinuxino_micro_defconfig
          - olimex_a33_olinuxino_defconfig
          - olimex_a64_olinuxino_defconfig
          - olimex_imx233_olinuxino_defconfig
          - olimex_stmp157_olinuxino_lime_defconfig
          - olpc_xo1_defconfig
          - olpc_xo175_defconfig
          - openblocks_a6_defconfig
          - orangepi_lite_defconfig
          - orangepi_lite2_defconfig
          - orangepi_one_defconfig
          - orangepi_one_plus_defconfig
          - orangepi_pc_defconfig
          - orangepi_pc_plus_defconfig
          - orangepi_r1_defconfig
          - orangepi_zero_defconfig
          - orangepi_zero_plus_defconfig
          - orangepi_zero_plus2_defconfig
          - pandaboard_defconfig
          - pc_x86_64_bios_defconfig
          - pc_x86_64_efi_defconfig
          - pcengines_apu2_defconfig
          - pine64_defconfig
          - pine64_sopine_defconfig
          - qemu_aarch64_ebbr_defconfig
          - qemu_aarch64_sbsa_defconfig
          - qemu_aarch64_virt_defconfig
          - qemu_arm_ebbr_defconfig
          - qemu_arm_versatile_defconfig
          - qemu_arm_vexpress_defconfig
          - qemu_arm_vexpress_tz_defconfig
          - qemu_m68k_mcf5208_defconfig
          - qemu_m68k_q800_defconfig
          - qemu_microblazebe_mmu_defconfig
          - qemu_microblazeel_mmu_defconfig
          - qemu_mips32r2_malta_defconfig
          - qemu_mips32r2el_malta_defconfig
          - qemu_mips32r6_malta_defconfig
          - qemu_mips32r6el_malta_defconfig
          - qemu_mips64_malta_defconfig
          - qemu_mips64el_malta_defconfig
          - qemu_mips64r6_malta_defconfig
          - qemu_mips64r6el_malta_defconfig
          - qemu_nios2_10m50_defconfig
          - qemu_or1k_defconfig
          - qemu_ppc_bamboo_defconfig
          - qemu_ppc_e500mc_defconfig
          - qemu_ppc_g3beige_defconfig
          - qemu_ppc_mac99_defconfig
          - qemu_ppc_mpc8544ds_defconfig
          - qemu_ppc64_e5500_defconfig
          - qemu_ppc64_pseries_defconfig
          - qemu_ppc64le_powernv8_defconfig
          - qemu_ppc64le_pseries_defconfig
          - qemu_riscv32_virt_defconfig
          - qemu_riscv64_nommu_virt_defconfig
          - qemu_riscv64_virt_defconfig
          - qemu_s390x_defconfig
          - qemu_sh4_r2d_defconfig
          - qemu_sh4eb_r2d_defconfig
          - qemu_sparc_ss10_defconfig
          - qemu_sparc64_sun4u_defconfig
          - qemu_x86_64_defconfig
          - qemu_x86_defconfig
          - qemu_xtensa_lx60_defconfig
          - qemu_xtensa_lx60_nommu_defconfig
          - raspberrypi_defconfig
          - raspberrypi0_defconfig
          - raspberrypi0w_defconfig
          - raspberrypi2_defconfig
          - raspberrypi3_64_defconfig
          - raspberrypi3_defconfig
          - raspberrypi3_qt5we_defconfig
          - raspberrypi4_64_defconfig
          - raspberrypi4_defconfig
          - raspberrypicm4io_64_defconfig
          - raspberrypicm4io_defconfig
          - raspberrypizero2w_defconfig
          - riotboard_defconfig
          - rock_pi_n8_defconfig
          - rock64_defconfig
          - rockpro64_defconfig
          - roseapplepi_defconfig
          - s6lx9_microboard_defconfig
          - sheevaplug_defconfig
          - sipeed_lichee_rv_defconfig
          - sipeed_lichee_rv_dock_defconfig
          - sipeed_maix_bit_defconfig
          - sipeed_maix_bit_sdcard_defconfig
          - sipeed_maix_dock_defconfig
          - sipeed_maix_dock_sdcard_defconfig
          - sipeed_maix_go_defconfig
          - sipeed_maix_go_sdcard_defconfig
          - sipeed_maixduino_defconfig
          - sipeed_maixduino_sdcard_defconfig
          - snps_arc700_axs101_defconfig
          - snps_archs38_axs103_defconfig
          - snps_archs38_haps_defconfig
          - snps_archs38_hsdk_defconfig
          - socrates_cyclone5_defconfig
          - solidrun_clearfog_defconfig
          - solidrun_clearfog_gt_8k_defconfig
          - solidrun_macchiatobin_defconfig
          - spike_riscv64_defconfig
          - stm32f429_disco_xip_defconfig
          - stm32f469_disco_sd_defconfig
          - stm32f469_disco_xip_defconfig
          - stm32f769_disco_sd_defconfig
          - stm32mp157a_dk1_defconfig
          - stm32mp157c_dk2_defconfig
          - stm32mp157c_odyssey_defconfig
          - terasic_de10nano_cyclone5_defconfig
          - toradex_apalis_imx6_defconfig
          - ts4900_defconfig
          - ts5500_defconfig
          - ts7680_defconfig
          - uevm5432_defconfig
          - versal_vck190_defconfig
          - visionfive_defconfig
          - visionfive2_defconfig
          - wandboard_defconfig
          - warp7_defconfig
          - warpboard_defconfig
          - zynq_microzed_defconfig
          - zynq_qmtech_defconfig
          - zynq_zc706_defconfig
          - zynq_zed_defconfig
          - zynqmp_kria_kv260_defconfig
          - zynqmp_zcu102_defconfig
          - zynqmp_zcu106_defconfig
    # continue-on-error: true # allow boards to continue even if one fails
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Enable ccache
        uses: actions/cache@v3
        with:
          path: output
          key: build_cache-${{ matrix.board_name }}-${{ github.sha }}
          restore-keys: build_cache-${{ matrix.board_name }}-
      - name: generate config
        run: make ${{ matrix.board_name }}
      - name: build
        run: make
      - name: upload generated images
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.board_name }}-images
          path: output/images/**.img*
